use [GettingStarted]
Insert into Suppliers values (    1,'Logitech','7022693457','292 Kaiser Drive Fre',10, 56.00)
Insert into Suppliers values (    2,'Sony','8004887669','8281 NW 107 Terrace', 5, 39.00)
Insert into Suppliers values (    3,'Hewlett-Packard','650857150','21 Hanover Street', 3, 78.00)
Insert into Products values (    1,'Apple 2 GB iPod Nano','Apple 2 GB iPod Nano',    2,  1000.00,    10)
Insert into Products values (    2,'SONY PSP console','SONY PSP console',    1,   527.14,     0)
Insert into Products values (    3,'SD Card 1024MB','SD Card 1024MB',    2,    99.99,     0)
Insert into Products values (    4,'IRIVER H10 6GB','IRIVER H10 6GB',    3,    67.60,     0)
Insert into Products values (    5,'Logitech G5 Laser Mouse','Logitech G5 Laser Mouse',    2,    69.00,     0)
Insert into Products values (    6,'Logitech Z-2300 Speaker System','Logitech Z-2300 Speaker System',    1,   143.00,     0)
Insert into Products values (    7,'HP iPaq hw6515 Mobile Messenger','HP iPaq hw6515 Mobile Messenger',    1,   439.00,     0)
Insert into Products values (    8,'Key Chain With LED Light','Key Chain With LED Light',    1,     2.54,     0)
Insert into Products values (    9,'Nature Sound Relaxation Humidifier','Nature Sound Relaxation Humidifier',    1,    37.90,     0)
Insert into Products values (   10,'Copenhagen Portable TFT LCD','Copenhagen Portable TFT LCD',    2,   350.56,     0)
Insert into Products values (   11,'Talking Blood Pressure Monitor','Talking Blood Pressure Monitor',    2,   123.00,     0)
Insert into Products values (   12,'Undercover Surveyor Binocular','Undercover Surveyor Binocular',    2,    90.40,     0)
Insert into Products values (   13,'Mosquito Repelling Wrist Watch','Mosquito Repelling Wrist Watch',    2,     5.10,     0)
Insert into Products values (   14,'Infrared Thermometer Gun','Infrared Thermometer Gun',    3,    10.49,     2)
Insert into Products values (   15,'1.3 Mega Digital Binocular Camera','1.3 Mega Digital Binocular Camera',    3,   785.00,     3)
Insert into Products values (   16,'Copenhagen Slim Portable DVD','Copenhagen Slim Portable DVD',    3,   214.00,     4)
Insert into Products values (   17,'KaraMax Karaoke Portable Microphone','KaraMax Karaoke Portable Microphone',    2,   160.50,     7)
Insert into Products values (   18,'Ultra Zoom Binoculars','Ultra Zoom Binoculars',    3,   250.00,     8)
Insert into Products values (   19,'2.4 GHz Video Camera Color Pen','2.4 GHz Video Camera Color Pen',    2,   178.00,     1)
Insert into Products values (   20,'Pocket Electronic Whistle','Pocket Electronic Whistle',    1,     2.99,    10)
Insert into Products values (   21,'Robot Vacuum Cleaner','Robot Vacuum Cleaner',    1,   230.00,    10)
Insert into Products values (   22,'Home Hot Dog Grill','Home Hot Dog Grill',    1,    80.00,    20)
Insert into Products values (   23,'Ultra Slim 22 Channel Digital Walkie Talkie','Ultra Slim 22 Channel Digital Walkie Talkie',    2,    43.00,     2)
Insert into Products values (   24,'G-force Giant Face Atomic Clock With Thermometer','G-force Giant Face Atomic Clock With Thermometer',    2,    32.00,     4)
Insert into Products values (   25,'Magic Mister Lamp and Fog Humidifier Fall','Magic Mister Lamp and Fog Humidifier Fall',    3,    53.00,     6)
Insert into Products values (   26,'Memory Foam Seat Cushion','Memory Foam Seat Cushion',    1,    19.90,     7)
Insert into Products values (   27,'Autobahn Valet Key Chain Led Light','Autobahn Valet Key Chain Led Light',    2,     3.70,     8)
Insert into Products values (   28,'Zen Humidifier LED Lamp with Water Fall Effect','Zen Humidifier LED Lamp with Water Fall Effect',    2,    55.90,     9)
Insert into Products values (   29,'SUSITA All-Weather Digital Handheld Compass light','SUSITA All-Weather Digital Handheld Compass light',    1,    19.00,    10)
Insert into Products values (   30,'HealthCare Foldable Full Body Massage Lounger','HealthCare Foldable Full Body Massage Lounger',    1,   199.95,    12)
Insert into Products values (   31,'Copenhagen Noise-Crippling Headphones','Copenhagen Noise-Crippling Headphones',    1,    59.00,    10)
Insert into Products values (   32,'Garmin Street Pilot C330 GPS en','Garmin Street Pilot C330 GPS en',    1,   897.55,     5)
Insert into Products values (   33,'LighterCam','LighterCam',    2,    47.00,     5)
Insert into Products values (   34,'Portable Ice Maker','Portable Ice Maker',    2,   286.00,     5)
Insert into Products values (   35,'Ergo-Thermodynamic Synchronized Executive Chair','Ergo-Thermodynamic Synchronized Executive Chair',    2,   495.80,     5)
Insert into Products values (   36,'Master Survival Power Supply Flashlight','Master Survival Power Supply Flashlight',    2,    14.32,     4)
Insert into Products values (   37,'Weather Station Atomic Wall Clock','Weather Station Atomic Wall Clock',    1,    54.85,     5)
Insert into Products values (   38,'Single Digital Walkie Talkie Wristwatch','Single Digital Walkie Talkie Wristwatch',    1,    43.90,     5)
Insert into Countries values (    1,'Israel')
Insert into Countries values (    2,'Italy')
Insert into Countries values (    3,'France')
Insert into Countries values (    4,'Japan')
Insert into Countries values (    5,'New Zealand')
Insert into Countries values (    6,'China')
Insert into Countries values (    7,'South Africa')
Insert into Countries values (    8,'Korea')
Insert into Countries values (    9,'United Kingdom')
Insert into Countries values (   10,'Brazil')
Insert into Countries values (   11,'Canada')
Insert into Countries values (   12,'Germany')
Insert into Countries values (   13,'Greece')
Insert into Countries values (   14,'Hungary')
Insert into Countries values (   15,'India')
Insert into Countries values (   16,'Poland')
Insert into Countries values (   17,'Russia')
Insert into Countries values (   18,'Romania')
Insert into Countries values (   19,'Spain')
Insert into Countries values (   20,'Switzerland')
Insert into Countries values (   21,'Thailand')
Insert into Countries values (   22,'USA')
Insert into Countries values (   23,'Netherlands')
Insert into Cities values (   10,  101,'Brasilia')
Insert into Cities values (   10,  102,'Rio de Janeiro')
Insert into Cities values (   10,  103,'Sao Paulo')
Insert into Cities values (   11,  201,'Edmonton')
Insert into Cities values (   11,  202,'Vancouver')
Insert into Cities values (   11,  203,'Winnipeg')
Insert into Cities values (   11,  204,'Halifax')
Insert into Cities values (   11,  205,'Ottawa')
Insert into Cities values (   11,  206,'Toronto')
Insert into Cities values (   11,  207,'Montreal')
Insert into Cities values (    6,  301,'Beijing')
Insert into Cities values (    6,  302,'Hong Kong')
Insert into Cities values (    6,  303,'Shanghai')
Insert into Cities values (    3,  401,'Paris')
Insert into Cities values (   12,  501,'Berlin')
Insert into Cities values (   12,  502,'Frankfurt')
Insert into Cities values (   13,  601,'Athens')
Insert into Cities values (   14,  701,'Budapest')
Insert into Cities values (   15,  801,'Kolkata')
Insert into Cities values (   15,  802,'Mumbai')
Insert into Cities values (   15,  803,'New Delhi')
Insert into Cities values (    1,  901,'Tel Aviv')
Insert into Cities values (    1,  902,'Jerusalem')
Insert into Cities values (    1,  903,'Haifa')
Insert into Cities values (    1,  904,'Eilat')
Insert into Cities values (    1,  905,'Ramat-Gan')
Insert into Cities values (    1,  906,'Givatayim')
Insert into Cities values (    2, 1001,'Rome')
Insert into Cities values (    2, 1002,'Verona')
Insert into Cities values (    2, 1003,'Venice')
Insert into Cities values (    2, 1004,'Florence')
Insert into Cities values (    4, 1101,'Tokyo')
Insert into Cities values (   23, 1201,'Amsterdam')
Insert into Cities values (    5, 1301,'Wellington')
Insert into Cities values (   16, 1401,'Warsaw')
Insert into Cities values (   18, 1501,'Bucharest')
Insert into Cities values (   17, 1601,'Kamchatka')
Insert into Cities values (   17, 1602,'Moscow')
Insert into Cities values (   17, 1603,'Vladivostok')
Insert into Cities values (    7, 1701,'Cape Town')
Insert into Cities values (    7, 1702,'Johannesburg')
Insert into Cities values (   19, 1801,'Barcelona')
Insert into Cities values (   19, 1802,'Madrid')
Insert into Cities values (   20, 1901,'Geneva')
Insert into Cities values (   20, 1902,'Zurich')
Insert into Cities values (   21, 2001,'Bangkok')
Insert into Cities values (    9, 2101,'London')
Insert into Cities values (   22, 2201,'Montgomery')
Insert into Cities values (   22, 2202,'Phoenix')
Insert into Cities values (   22, 2203,'Los Angeles')
Insert into Cities values (   22, 2204,'San Francisco')
Insert into Cities values (   22, 2205,'Denver')
Insert into Cities values (   22, 2206,'Washington')
Insert into Cities values (   22, 2207,'Atlanta')
Insert into Cities values (   22, 2208,'Honolulu')
Insert into Cities values (   22, 2209,'Chicago')
Insert into Cities values (   22, 2210,'Indianapolis')
Insert into Cities values (   22, 2211,'New Orleans')
Insert into Cities values (   22, 2212,'Boston')
Insert into Cities values (   22, 2213,'Detroit')
Insert into Cities values (   22, 2214,'Minneapolis')
Insert into Cities values (   22, 2215,'New York')
Insert into Cities values (   22, 2216,'Philadelphia')
Insert into Cities values (   22, 2217,'Houston')
Insert into Cities values (   22, 2218,'Seattle')
